language: go
go: "1.14"
before_script:
  - go vet ./...
install:
  - go get -u golang.org/x/tools/cmd/godoc
  - ./travis_scripts/get_ninja.sh
  - ./travis_scripts/get_bood.sh
script:
  - cd $GOPATH/src/github.com/dkalytovskyi/go-lab-2/build
  - ../travis_scripts/create_custom_bood.sh
  - bood 
